defaults: &defaults
  domain: lopr.dev
  host: lopr.dev
  name: Sexy Younger You
  aweber:
    key: AkpsFMLYvEZmViiLZZ3GzTvh
    secret: O92GYO04y9GKfa33nwqJh68ZOOpdRGk1DkStCgdC
    access_token: AgGAr7PE25DpAEocf12J3OAg
    access_secret: MEPJdAFFC1So1E5kO1W8fwhZXdulWpqhtLCerexN
  oneshoppingcart:
    id: 209677
    mid: 5655D14A-8099-4AC3-A5FF-6D8F0F7123B8
    key: 1E286772AAAA48359A5B18597B5B626A

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  domain: sexyyoungeryou.herokuapp.com
  host: sexyyoungeryou.herokuapp.com