defaults: &defaults
  domain: lopr.dev
  mail_domain: lopr.dev
  assets:
    storage: file
  aws:
    key: AKIAJ4PXJBGOZ6U7VJBA
    secret: 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
  aweber:
    key: AkF7gUyyb4BRvblnk83cei8w
    secret: EvSThf3ZBSWWRPLD7VfwkKjk8ohRJud6Dstv7lu7
    verifier: 3vk9zk
    access_token: AgsE7lsgCyE4kPMwej43tJZU
    access_secret: hmN2Ixd5rxt3zoWLeSVfYYpkCePxbZ5NnPhPqmfi
  oneshoppingcart:
    key: F81ADCC1F81042A8BCBCCFADEB0BE80C

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  domain: loveonpurposerevolution.com
  mail_domain: www.loveonpurposerevolution.com
  assets:
    storage: fog