theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: none
content_css: "/assets/content.css"
plugins:
  - inlinepopups
  - paste
  - uploadimage
theme_advanced_buttons1: 
  - bold
  - italic
  - underline
  - strikethrough
  - separator
  - justifyleft
  - justifycenter
  - justifyright
  - separator
  - formatselect
  - styleselect
  - removeformat
theme_advanced_buttons2: "bullist,numlist,separator,outdent,indent,separator,undo,redo,separator,link,unlink,separator,hr,image,uploadimage"
theme_advanced_buttons3: ""
theme_advanced_blockformats: "p,h3,h4"
external_image_list_url: "/admin/images.js"
style_formats:
  - title: 'Red Text'
    inline: 'span'
    classes : 'red'
  - title: 'Orange Text'
    inline: 'span'
    classes : 'orange'
  - title: 'Green Text'
    inline: 'span'
    classes : 'green'
  - title: 'Testimonials'
    block: 'div'
    classes: 'testimonials'
    wrapper: true
  - title: 'Image Left'
    selector: 'img'
    classes: 'left-align'
  - title: 'Image Right'
    selector: 'img'
    classes: 'right-align'
